name: Build and Release Plugin

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Gewährt Schreibzugriff auf das Repository

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Build plugin with Gradle
        run: ./gradlew buildPlugin

      - name: List build artifacts
        run: ls -l build/distributions/

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/distributions/*.zip
          tag_name: v${{ github.run_number }}
          name: Release v${{ github.run_number }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}